ARG USER="clajus"
FROM registry.opensuse.org/opensuse/distrobox:latest
RUN zypper --non-interactive install --no-recommends \
    git \
    git-credential-libsecret \
    starship \
    bat \
    ripgrep \
    zoxide \
    fzf \
    neovim \
    atuin \
    && zypper clean
# Mount coniguration files.
VOLUME ~/.config/nvim:/home/$USER/.config/nvim
VOLUME ~/.config/starship:/home/$USER/.config/starship
VOLUME ~/.config/atuin:/home/$USER/.config/atuin
# Set nushell as default shell
RUN chsh -s /urs/bin/nu $USER
